name: Deploy

on: 
  push: 
    branches: [main]

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 184.73.149.8 >> ~/.ssh/known_hosts


          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-184-73-149-8.compute-1.amazonaws.com << 'EOF'
            set -e  # Exit on error
            cd timchem || exit 1
            git pull origin main
            cd my-app
            chmod 400 cicd-deploy.sh
            ./cicd-deploy.sh
          EOF
